### ISSUE TITLE
Each theme contains Git objects

### ISSUE THREAD

**Issue by fabiorush92** [AeolusUX/ArkOS-R3XS#11]
Hi,
Into latest release, each theme contains .git folder, .gitattributes and .gitignore.
These files maybe came from a folder copy and are useless for the theme functionality.
By removing these files and folders from the release image, you can speed up first initialization and save some more space! ✌

**Comment by AeolusUX** [comment]
These files are for version control of the themes. It's supposed to be there for you to be able to update to latest version of the theme. You could opt to delete them if you don't want to update but they are needed so I won't be removing anything. They are not useless as you say.
