### ISSUE TITLE
ArkOS 03302024 - Retroarch won't load games

### ISSUE THREAD

**Issue by cobaltgit** [AeolusUX/ArkOS-R3XS#12]
Reporting for clarity, already discussed over Discord: games will only load if Retrorun or a standalone emulator is selected via the emulation settings, otherwise attempting to launch a game using Retroarch (Auto in emulator settings) will crash and return to the ArkOS menu.

**Comment by r0ckarong** [comment]
Start of the convo: https://discord.com/channels/741895796315914271/1185499524257558600/1224389755069009970
