### ISSUE TITLE
N64 Mupen64Plus Saves + States + Screenshots not working 

### ISSUE THREAD

**Issue by DeusAbsconditus** [AeolusUX/ArkOS-R3XS#14]
Hello,

there seems to be an issue with the N64 emulator Mupen64plus when creating saves, save states, and screenshots.
Upon closer examination, it appears that incorrect paths are specified in the emulator's configuration file (/home/ark/.config/mupen64plus/mupen64plus.cfg).
The entries ScreenshotPath, SaveStatePath, and SaveSRAMPath point to a directory named "roms2".
However, this directory seems to lead nowhere in an ArkOS installation with only one SD card.

It might be necessary to change the entries in the configuration file to point to the "roms" directory instead. This directory should definitely exist.

EDIT:
Installed Version: ArkOS R3XS V2.0 (02232024)
The "Switch to SD2 for Roms" script was not executed.

EDIT2:
Updated to the latest version. Before that, I restored the config with the wrong paths. After update still the wrong paths.

**Comment by AeolusUX** [comment]
Have you tried doing Switch to Main SD? That script changes the mupen64plus.cfg paths back to /roms/ instead of /roms2/

**Comment by DeusAbsconditus** [comment]
Where do I find this?

**Comment by AeolusUX** [comment]
It's only for this image since I might've tried the switch to sd2 script since that's not working for my 3/30/2024 update, I'll make sure future images are set to default.
