### ISSUE TITLE
Mupen64Plus-Next libretro core does not work

### ISSUE THREAD

**Issue by ksielick** [AeolusUX/ArkOS-R3XS#15]
New R36S console. ArkOS R3XS V2.0 (04022024)

Retroarch -> Load Core -> Nintendo - Nintendo 64 (MupenPlus-Next)

Load any ROM results in "Failed to open libretto core"

**Comment by AeolusUX** [comment]
Why were you loading this with retroarch?

**Comment by ksielick** [comment]
Because launching N64 games from UI also does not work with that core.

I also have the latest ArkOs on RGB30 and use Mupen64Plus-Next core without any problems.

**Comment by AeolusUX** [comment]
Yes because christian pushed an update yesterday. Cheers!
