### ISSUE TITLE
Can't enable 2nd SD card

### ISSUE THREAD

**Issue by Sysatic** [AeolusUX/ArkOS-R3XS#16]
It says it can't find any exFAT, ext4, NTFS, ... -formatted SD.

2x SanDisk Extreme PRO 64GB, brand-new
R36S
AeolusUX/ArkOS-R3XS, just downloaded

Thanks in advance!

**Comment by AeolusUX** [comment]
Is it red. I have a [compatibility list](https://docs.google.com/spreadsheets/d/1gWxtr-GmwWop-_qGUq022RXxK2aTLpPg9Qra68TQLI8/htmlview#gid=0) that lists sandisk as spotty. Try another card.

**Comment by Sysatic** [comment]
Geez! I didn't knew there are any compatibility issues with SD cards. I just ordered an Samsung Evo Select.
Thank you very much!
