### ISSUE TITLE
RTL8188 + USB-C adapter will not connect to a WPA2/WPA3 wifi network on ArkOS R3XS V2.0 (04022024)

### ISSUE THREAD

**Issue by CSFFlame** [AeolusUX/ArkOS-R3XS#17]
ArkOS R3XS V2.0 (04022024)
R36S

An RTL8188 + USB-C adapter will not connect to a WPA2/WPA3 wifi network on ArkOS.  It will connect to a WPA/WPA2 network.
It will connect to both networks on AmberELEC prerelease-20240331_2102

The error message presented is: "Activation Failed.  Secrets were required, but not provided..."

The router is a Xiaomi AX3000T running the latest openwrt snapshot.  Multiple other devices are connected at WPA3.

Exact Adapter: https://www.aliexpress.us/item/3256805200687461.html
Exact RTL8188 device: https://www.aliexpress.us/item/3256805937479543.html

I tried another usb-c adapter I got years ago, with the same result on both systems.

802.11r is off.

WPA2/WPA3 (unable to connect):
![badwifi1](https://github.com/christianhaitian/arkos/assets/105515466/6ce94874-d6f3-41e2-89ad-d3e59f8c2e9a)
![badwifi2](https://github.com/christianhaitian/arkos/assets/105515466/dbc46325-151a-4ea1-91aa-4369a62fe7d5)
WPA/WPA2 (able to connect):
![goodwifi1](https://github.com/christianhaitian/arkos/assets/105515466/dc57c3d3-d9d0-4a8d-8c24-11286174c252)
![goodwifi2](https://github.com/christianhaitian/arkos/assets/105515466/c918da1f-3316-403a-8c98-eaadefe09fca)

**Comment by AeolusUX** [comment]
The RTL8188 has variations so not sure if I can help you with this unless we have the same ones. You could try using this file if it would fix your problem. I compiled it long ago for one of my dongles and always forget to add into my builds. [rtl8188fu.zip](https://github.com/AeolusUX/ArkOS-R3XS/files/14892707/rtl8188fu.zip) This one is for the RTL8188FU the RTL8188FTV can also use this. By default ArkOS uses the rtl8192cu driver.

1. Go to ./usr/lib/modules/4.4.189/kernel/drivers/net/wireless then paste the .ko file
2. in ssh do `sudo depmod`

**Comment by manipuladordedados** [comment]
Same thing happens here, even with the same chip, but not only with it. I've tested with various other brands' chips, and they manage to recognize and detect the connections, but it always ends up giving the same error.

> The RTL8188 has variations so not sure if I can help you with this unless we have the same ones. You could try using this file if it would fix your problem. I compiled it long ago for one of my dongles and always forget to add into my builds. [rtl8188fu.zip](https://github.com/AeolusUX/ArkOS-R3XS/files/14892707/rtl8188fu.zip) This one is for the RTL8188FU the RTL8188FTV can also use this. By default ArkOS uses the rtl8192cu driver.
> 
>     1. Go to ./usr/lib/modules/4.4.189/kernel/drivers/net/wireless then paste the .ko file
> 
>     2. in ssh do `sudo depmod`

I tested it and it didn't solve the issue.
