### ISSUE TITLE
RTL8188 + USB-C adapter runs very hot and severely increases battery drain on ArkOS R3XS V2.0 (04022024)

### ISSUE THREAD

**Issue by CSFFlame** [AeolusUX/ArkOS-R3XS#18]
ArkOS R3XS V2.0 (04022024)
R36S

An RTL8188 + USB-C adapter will heat up significantly and drain the battery, even if idle or not connected to wifi.

Exact Adapter: https://www.aliexpress.us/item/3256805200687461.html
Exact RTL8188 device: https://www.aliexpress.us/item/3256805937479543.html

I tried another usb-c adapter I got years ago, with the same result on both systems.

This issue is not present in AmberELEC.

ArkOS R3XS V2.0 (04022024) is on the left, AmberELEC prerelease-20240331_2102 is on the right, Ambient 78F:

Start:
![Start](https://github.com/christianhaitian/arkos/assets/105515466/83744352-6e1a-4394-a2b9-525c85d4cf32)
1 minute:
![1minute](https://github.com/christianhaitian/arkos/assets/105515466/562e3568-23d4-41e1-a265-9a9763f6b33f)
2 minutes:
![2minutes](https://github.com/christianhaitian/arkos/assets/105515466/debf2e94-68b4-40b4-8aba-8b8b735fa442)
3 minutes:
![3minutes](https://github.com/christianhaitian/arkos/assets/105515466/786a8a35-a421-4eec-9c9e-cf58bd1110bf)
5 minutes:
![5minutes](https://github.com/christianhaitian/arkos/assets/105515466/9d8573c7-21da-456a-b0b8-3d1976c50e9f)
15 minutes:
![15minutes](https://github.com/christianhaitian/arkos/assets/105515466/5cfe9bb6-6e64-43c4-8d2a-d4d7dd318f61)
15 minutes:
![15minutes2](https://github.com/christianhaitian/arkos/assets/105515466/3e3bbaf0-8620-4db9-a65e-f5926a7a1779)

**Comment by AeolusUX** [comment]
This is a common issue that is happening with rtl8xxxu chipset based wifi adapters. These wifi adapters are known to have bad stability and performance with Linux using the built-in kernel drivers for this chipset. You could try the kernel driver I posted on the other issue and see if that fixes this for you. If not I suggest that you just get a better dongle altogether this chipset is the absolute worst to use for anything linux.
