### ISSUE TITLE
Reset with low battery while in game corrupts save file

### ISSUE THREAD

**Issue by FurtadoPires** [AeolusUX/ArkOS-R3XS#23]
I was playing with about 20% battery when accidentally  hit the reset button and the device rebooted with the white lines on the screen, so I charged the battery but once I started to play again all the saves (made by the rom, not save states) from the game were gone (despite the file still existing in the folder).

Maybe ArkOS could have a fail safe to prevent this from happening, like creating copies from the savefile in case the battery starts to run low, and delete automatically in case of a clean exit, or something similar that could prevent this problem from happening.

To reproduce:
-Play a game using only saves from the rom (in my case was a snes game)
-Let the battery go then hit the reset button (until you get the low battery screen then turn off)
-Charge the device and check if the saves are ok

**Comment by AeolusUX** [comment]
For suggestions on ArkOS itself please report it on the main ArkOS repo.
