### ISSUE TITLE
The hotkey FN using for fast forward in Retroarch by default

### ISSUE THREAD

**Issue by VolodymyrDA** [AeolusUX/ArkOS-R3XS#25]
The hotkey FN (button 16) using for fast forward in Retroarch by default.
Please remove it.

**Comment by AeolusUX** [comment]
You can remove it on retroarch yourself. I'm not removing it because it is how I use it and this community image (fork) is made for how I use my R36S.

**Comment by a1b0hph0b1a** [comment]
I found this annoying too and did change it in RetroArch settings...

For those who are looking for how to change...

Main Menu (you know, with systems) --> RetroArch --> Settings --> Hotkeys 

Scroll down to "Fast-Foward (Hold)", press Y to clear the currently set button, press A and then hold the button you want for fast forward.
