### ISSUE TITLE
Core selection. 

### ISSUE THREAD

**Issue by fabinhojcr** [AeolusUX/ArkOS-R3XS#29]
Could it be that in the next versions you could implement the function of choosing the core I want to use for each system?

**Comment by AeolusUX** [comment]
What do you mean? That is already there you know.

**Comment by fabinhojcr** [comment]
@AeolusUX My games were in the mame folder and I didn't have the option to change the cores, christianhaitian recommended that I change the roms to the arcade folder, this solved the problem.
