### ISSUE TITLE
Panel 4 (V5)

### ISSUE THREAD

**Issue by chronoss09** [AeolusUX/ArkOS-R3XS#30]
Juts to know it's for wich console ?

Tool page don't work, i put the file and click on Identify my screen and nothing apear :(

**Comment by AeolusUX** [comment]
People with panel 4?
I don't know what you're doing wrong can you elaborate? I've had people try it and it works for them.

**Comment by chronoss09** [comment]
I have a panel 3 and the first os work but splash don't work with launchimage too...
