### ISSUE TITLE
PortMaster-2Ship2Harkinian

### ISSUE THREAD

**Issue by Vendo233** [AeolusUX/ArkOS-R3XS#34]
https://github.com/JeodC/PortMaster-2Ship2Harkinian/issues/1#issue-2329704762 

SOH2 port log, game would not start

log

./2s2h.elf: /lib/aarch64-linux-gnu/libc.so.6: version GLIBC_2.33' not found (required by /roms/ports/soh2/libs/libzip.so.4) ./2s2h.elf: /lib/aarch64-linux-gnu/libc.so.6: version GLIBC_2.33' not found (required by /roms/ports/soh2/libs/libcrypto.so.3)
./2s2h.elf: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /roms/ports/soh2/libs/libcrypto.so.3)

R36S with latest 5.24 OS update

**Comment by AeolusUX** [comment]
I don't think this has worked before.
