### ISSUE TITLE
Outdated mupen64plus.ini in 05242024

### ISSUE THREAD

**Issue by upwhatever** [AeolusUX/ArkOS-R3XS#36]
in ArkOS 05242024 the file /opt/mupen64plus/mupen64plus.ini is very outdated (filesystem date from 2020) and is therefore missing some entries that are necessary to boot certain roms with mupen64plus stand alone, e.g. CountPerOp=3 for Wave Race 64 Rumble Edition. Replacing the file with the latest version[1] fixes the issue.

[1} https://raw.githubusercontent.com/mupen64plus/mupen64plus-core/master/data/mupen64plus.ini

btw: There are some emulationstation files in /opt/mupen64plus which probably do not belong there.

**Comment by AeolusUX** [comment]
Will be added on the next update along with other fixes for mupen64plus.
