### ISSUE TITLE
After the update, USB tethering was lost.

### ISSUE THREAD

**Issue by jurandy007** [AeolusUX/ArkOS-R3XS#37]
I noticed that in this latest version it only charges the phone and does not enable the option to activate USB tethering like the stock system.

Are there any solutions or options in ArkOS for this?

**Comment by AeolusUX** [comment]
Nothing’s changed it’s not ArkOS fault. Check your device or cable. Usb Tethering is not advertised to work some do and some don’t nothing we can do about it. It’s best to buy a compatible dongle.

**Comment by jurandy007** [comment]
Sorry if I seemed offensive by just asking.

I wanted to say that in the ArkOs System that came with it it worked and in this one it didn't. (same cell phone and cable, yes I tested with different cables)

but thanks anyway

**Comment by AeolusUX** [comment]
That’s impossible as nothing has changed on the kernel since then. You might be missing a step on your procedure as the UI has changed other than that i’m reiterating that the best thing to do is get a compatible dongle.

**Comment by jurandy007** [comment]
I understand, I already have a Wifi dongle and use it, but I was curious about this function. I even thought it could be something that I didn't activate in the system settings.
