### ISSUE TITLE
[Question]Palm game for noob

### ISSUE THREAD

**Issue by Fr-Dae** [AeolusUX/ArkOS-R3XS#39]
Good morning,
I've probably done something wrong, but I can't run the downloaded games for palm os.

I have checked that I have the latest core for palmOS(mu).
Nothing is displayed in the main menu with the other systems.

I also tried in "retroarch" mode by manually selecting the zip of the game and the core, nothing launches.

If you have any ideas, I'm interested.

**Comment by AeolusUX** [comment]
https://github.com/christianhaitian/arkos/wiki/ArkOS-Emulators-and-Ports-information#palm-os

**Comment by Fr-Dae** [comment]
thank you, I've already looked at this documentation,
but there are no instructions on what to do, where to take the core, where to place it,


it's precisely because of the lack of instructions that I'm asking for help

**Comment by AeolusUX** [comment]
I've seen you've already been helped by christian on the main repo so I'm closing this.
