### ISSUE TITLE
Mednafen doesn't recognize inputs

### ISSUE THREAD

**Issue by AlSchadeck** [AeolusUX/ArkOS-R3XS#4]
Currently using 02/06/24 version and Mednafen emulator doesn't seem to recognize any inputs or shortcuts, tried on GBC/GBA and SNES and I can't play or exit the game, only way out is resetting the console.

**Comment by AeolusUX** [comment]
This seems to have been introduced in the 1/27/2024 update I'll be forwarding this issue on the main arkos repo.
