### ISSUE TITLE
The volume does not contain a recognized file system

### ISSUE THREAD

**Issue by OttoVHV** [AeolusUX/ArkOS-R3XS#46]
Good evening, I needed help, I'm trying to install Arkos 2.0 on my SD card, and it installs apparently normally, 3 partitions appear inside the card, the BOOT one I can access normally, but the other two don't allow me to access them , what do I do??

I have an R36s and I have no idea what I'm doing wrong

**Comment by AeolusUX** [comment]
This is not a software issue hence not really the right place to post this. This is not tech support for the device.

Have you inserted it into your device yet? If not do it. If yes go to disk management and select the easyroms partition and assign a letter to it. The other one is not accessible on windows and you don't need to access it anyway. If you need more info check the beginner's guide and countless youtube videos available on the net.
