### ISSUE TITLE
Microvision emulation display is cut off on R36S

### ISSUE THREAD

**Issue by ZoranLain** [AeolusUX/ArkOS-R3XS#49]
On R36S (I have the original display panel), Microvision emulation has a display issue. When I start a game (any rom), the display seem to be off. The screen seem to be cut off. It is as if the resolution is wrong.

**Comment by AeolusUX** [comment]
Really? Can you show an image? If resolution is wrong does it even matter for these kind of games?

**Comment by ZoranLain** [comment]
Sure.  Here are 2 photos.  You can see the play area is off to the side and go out of bound.   I also have the same game running on my old RG351P on ArkOS (wuMMLe fork).  That's what it supposed to look like. 
![ArkOS_MV_R36S](https://github.com/AeolusUX/ArkOS-R3XS/assets/76766564/f78361e9-75a0-4126-a339-8ea8e9bf8d8c)
![ArkOS_MV_RG351P](https://github.com/AeolusUX/ArkOS-R3XS/assets/76766564/47bfa6c3-f7b4-4920-b863-e9a204efcf88)

**Comment by AeolusUX** [comment]
Ok just got time to try and fix this. I found the issue and will add it for the next release. Was not able to find a proper .bmp and _snap.bmp for my device so I just tested with it bare xD

**Comment by AeolusUX** [comment]
Should be fixed with latest update.
