### ISSUE TITLE
Change boot picture?

### ISSUE THREAD

**Issue by newzealandpaul** [AeolusUX/ArkOS-R3XS#51]
Is is possible to change the boot picture without recompiling anything?

**Comment by AeolusUX** [comment]
Who said you need to recompile anything? Just add your bmp on the BMPs folder.

**Comment by newzealandpaul** [comment]
Thank you, I though it was more complicated. Also thank you @AeolusUX for making such a fantastic port.

**Comment by AeolusUX** [comment]
No worries mate, If you have any queries about the bmp format you can find the info [here](https://github.com/christianhaitian/arkos/wiki/Frequently-Asked-Questions---rg351mp#a-the-boot-logo-is-located-in-the-fat32-boot-partition--it-is-named-logobmp) along with other helpful bits that apply to the R36S.
