### ISSUE TITLE
NDS ART

### ISSUE THREAD

**Issue by Healer101015** [AeolusUX/ArkOS-R3XS#54]
I made some artwork for NDS, do you think it would be cool to put them in the project's optional?

**Comment by AeolusUX** [comment]
Can you share them here?

**Comment by Healer101015** [comment]
SURE
![bg_vh_c1](https://github.com/user-attachments/assets/275cff90-3f83-4744-96dd-5a4dc8590590)
![bg_vh_s0](https://github.com/user-attachments/assets/ba87a9a3-0cdc-43a7-aa5c-aaba8842b503)

**Comment by AeolusUX** [comment]
Looks nice do you have more? Could you share them as .zip files so I could upload them for people who wants them?

**Comment by Healer101015** [comment]
So far I have these
[all arts.zip](https://github.com/user-attachments/files/16474202/all.arts.zip)

**Comment by AeolusUX** [comment]
Great I'll make a new repo for it and include the ones I've modified.

**Comment by AeolusUX** [comment]
https://github.com/AeolusUX/arkos-ndsoverlay-gallery
