### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by RafaelLouz** [AeolusUX/ArkOS-R3XS#55]
I try some multiplayer (wi-fi) games on two R36s (first screen version and forth screen version), some games are ok, but Pokemon don´t work. I remember that gb, gbc and gba wasnt exactly a two player, but the conection was made by "game link". Arkos don´t have suport to emulator game link or I need some special configuration?

**Comment by AeolusUX** [comment]
You'd need to look for the cores that makes it work. You'd get better help on the subreddit or discord as there would be more people there that could answer your issue.
