### ISSUE TITLE
Black screen after splash screen.

### ISSUE THREAD

**Issue by arthurmohn** [AeolusUX/ArkOS-R3XS#61]
I just bought new SD cards to upgrade the ArkOS version on my R35S. After using rufus to load the iso into the sd card, i copied the rg351mp-kernel and rk3326-r35s-linux from my old card to the new one. After turning on the console, the ArkOS splash screen appears and after that is just a black screen. I left it running for 30 min but nothing. Any help with that, please?

**Comment by Resodx** [comment]
how do you fix this?
