### ISSUE TITLE
R33S hot keys not working on stand alone emulators

### ISSUE THREAD

**Issue by yuda00-1** [AeolusUX/ArkOS-R3XS#65]
Hotkeys using R3 or any analog buttons cannot be opened when using R33S due to the lack of analog buttons. Menus don't open in stand alone PSP and DS emulators hence game also cannot be exited. cannot also swap screen position on DS dual screen layout

**Comment by AeolusUX** [comment]
Yeah I might be updating it for this months release. I haven't been updating this much since there are only a few R33S before but now that they released it I might be doing updates for it soon.

**Comment by yuda00-1** [comment]
Please do. The R33s is a really good handheld

**Comment by AeolusUX** [comment]
This has been taken into account on the latest update. There will also be a single image for both the R33S and R35S/R36S from now on.
