### ISSUE TITLE
Unable to finish the installation

### ISSUE THREAD

**Issue by brcorreabr** [AeolusUX/ArkOS-R3XS#7]
I tried using "Rufus" and "USB image tool" to flash te image ArkOS_R35S-R36S_v2.0_02232024.img.xz to my SDCard, and after initiating installation on the device (R35S) an error occurs "/boot/expandtoexfat.sf: line 60: 633 Segmentation fault sudo mv -f -v /tempthemes/* /roms/themes".

![image](https://github.com/AeolusUX/ArkOS-R3XS/assets/4600137/51d84b92-fce6-49fe-9a8c-d54996dee6f9)

**Comment by AeolusUX** [comment]
So, what's wrong with it?
