### ISSUE TITLE
update seems not to work properly

### ISSUE THREAD

**Issue by Rathi401** [AeolusUX/ArkOS-R3XS#71]
Hello. Ich run the latest version of arkos, but when i try the update function, it says that i didnt wrote "OK". Any suggestions? Normally it should say that no update is available.

**Comment by AeolusUX** [comment]
You have to wait. The update is not ready yet. Everytime people post about this I move the timetable to another day 🤣

**Comment by Rathi401** [comment]
oh ok, thought the message is another :)
