### ISSUE TITLE
No available Wifi connections after installing 02-23-24 update

### ISSUE THREAD

**Issue by joeykala** [AeolusUX/ArkOS-R3XS#8]
ive used the .img file you provided for the new arkos 02-23-24 update for the R36s, everything updated fine, but now for some reason i cant connect to wifi on any of my R36s devices with this update. When i go to connect to wifi, no available wifi connections will show up. Ive tried multiple wifi adapters. Any idea how to fix this? thank you!

**Comment by AeolusUX** [comment]
Couldn't replicate the issue. I haven't touched anything from the drivers so it shouldn't be a problem. It's probably your otg adapter or the wifi dongles themselves.
